### PR TITLE
Use hasmap to find comment data #374

### PR DESCRIPTION
**Pull request by nook24**
This is my attempt to patch #374. Would be good if you could review this.
Signed-off-by: nook24 <info@nook24.eu>

### CODE REVIEW

**Comment by sni** [comment]
Now there is a `comment_hashtable` and a `comment_hashlist`. Have you checked if we need both by any chance?

**Comment by nook24** [comment]
Tbh, I'm not sure if I understand whats happening with `comment_hashlist` by 100%. It is only used by `comment *get_next_comment_by_host(char *host_name, comment *start)`. I think it is possible to get rid of it but I tried to touched as less code as possible.

How ever, by removing `comment_hashlist` we could also delete this:
https://github.com/naemon/naemon-core/blob/47002195d849455863c2fad7f1a440192ef6cce5/src/naemon/shared.c#L416-L437

**Review by sni — APPROVED** [review]
looks good

**Comment by sni** [comment]
could you please rebase this PR on the latest HEAD. This should also trigger the checks again.

**Comment by sni** [comment]
i made some changes and created https://github.com/naemon/naemon-core/pull/420

**Pull request closed without merging**
