### PR TITLE
Remove nullifying of service comment list before removal of a comment

### PR DESCRIPTION
**Pull request by jmacario24**
This pull request is to remove the nullifying of service comment list prior the removal of the comment from the list.

### CODE REVIEW

**Comment by nook24** [comment]
I guess this is fine as we do not nullify `temp_host->comments_list` either.

Could you please add one or two sentence about this issue this causes? Like did Naemon crash or something?

**Comment by jmacario24** [comment]
> I guess this is fine as we do not nullify `temp_host->comments_list` either.
> 
> Could you please add one or two sentence about this issue this causes? Like did Naemon crash or something?

Trying to access the comment list after a first delete will return an empty list as can be verified by call to number_of_service_comments after a delete.

**Comment by sni** [comment]
thanks for the clarification, i'll have a look. No idea why i did that 2 years ago...

**Review by sni — APPROVED** [review]

**Comment by sni** [comment]
thanks for submitting this PR. I guess it was a test leftover.

**Pull request merged**
