### PR TITLE
fix external command CHANGE_SVC_MODATTR

### PR DESCRIPTION
**Pull request by anfoe1111**
fix for issues #174 and #186

### CODE REVIEW

**Comment by sni** [comment]
I guess you are right :-)

**Comment by roengstrom** [comment]
Looks okay to me. Will run this PR internally and see if we can merge it.

**Comment by rhagman** [comment]
Would be nice to be able to test this so that we don't break it in the future.

**Comment by tsjondin** [comment]
Nice catch, though a test for the command is required for merge.

**Comment by sni** [comment]
The fact that we don't have test cases for all commands should not prevent this PR from being merged, especially if its just a simple typo fixed.

**Comment by tvestelind** [comment]
It's not just a typo, the functionality is changed.

I don't think it's unreasonable to demand a test for this, unless the test is very hard to write. That being said, we should help to check whether we can write such a test or not.

**Comment by tsjondin** [comment]
I believe a simple test, creating a host, a service and then running this command against the service is sufficient. Not all commands have to be tested in this test, just the functionality that has changed.

**Comment by tvestelind** [comment]
If making a test is hard then I can go with @sni's suggestion and merge it

**Pull request merged**
