### PR TITLE
Retain next_check schedule on restart (#224, #156)

### PR DESCRIPTION
**Pull request by jacobbaungard**
This commit ensures that the next_check schedule for hosts and services
are retained on Naemon restart, given that use_retained_scheduling_info
is enabled.

The logic is as follows:

- If use_retained_scheduling_info is disabled, set a random time (as
  before)
- If use_retained_schedule_info is enabled:
  - If we didn't miss the check during the restart, retain the old
    next_check time
  - If we missed one check, schedule the service/host within the next
    interval_length (usually 60 seconds)
  - If we missed more than one check, schedule the next check randomly.

We schedule missed checks within 60 seconds, rather than immediately in
order to do some load balacing. This is also the rationale for
scheduling the check randomly, in case we missed more than one check
(this indicates Naemon has been down for a longer period of time).

This fixes:
- https://github.com/naemon/naemon-core/issues/224
- https://github.com/naemon/naemon-core/issues/156
- [MON-10720](https://jira.op5.com/browse/MON-10720)

Signed-off-by: Jacob Hansen <jhansen@op5.com>

### CODE REVIEW

**Comment by sni** [comment]
thats great news, thanks

**Comment by jacobbaungard** [comment]
I think this is ready now.

- Added tests
- Fixed an issue from the previous commit (check_interval was in minutes instead of seconds as it should be).

**Comment by jacobbaungard** [comment]
@nook24, @jvigna, how does the logic in this PR sound for you guys? You think it would solve the problems you have reported?

**Comment by jvigna** [comment]
Look very good to me!

**Comment by jacobbaungard** [comment]
I will go ahead and merge this, this afternoon unless there are any objections.

**Comment by sni** [comment]
i was on vacation... :-) no objections.

**Pull request merged**
