### PR TITLE
Add host_down_disable_service_checks config option

### PR DESCRIPTION
**Pull request by sni**
Add option to *not* check services if their host is down.

references:
      - https://github.com/NagiosEnterprises/nagioscore/commit/05e1dda8ccaa9d633b22b11a555d67724930a3e7

### CODE REVIEW

**Comment by jacobbaungard** [comment]
Looks interesting. Perhaps we should have a unit test for this?

**Comment by jacobbaungard** [comment]
I think this change is good, but would really like to see a short test for it as well. I think we have a reasonable test setup, so we might as well use it (useful for guarding against future regressions etc etc).

**Comment by sni** [comment]
i just didn't have time to look further into this. I will add a simple test case.

**Comment by jacobbaungard** [comment]
This should do, I think. 

[0001-Test-host_down_disable_service_checks.txt](https://github.com/naemon/naemon-core/files/2663322/0001-Test-host_down_disable_service_checks.txt)

**Comment by sni** [comment]
thanks, i will add that one

**Pull request closed without merging**
