### PR TITLE
op5 master merge

### PR DESCRIPTION
**Pull request by catharsis**
At long last, here's a first revision of a merge between op5's master and upstream's. I'm expecting some breakage - but nothing *too* serious. Things build fine on my end on Arch & CentOS 6, but I'm bound to have missed something in a merge this large.

### CODE REVIEW

**Comment by nook24** [comment]
Hi,
great job :)
I looks like the check_interval issue #117 is still in there. Can you please add the patch as well to the PR?
Looking forward to test the new version

**Comment by catharsis** [comment]
@nook24 Perhaps it'd be better to do that as a separate merge. We need the synchronization practice, anyways, and a live bullet seems as good as any to get some experience and perhaps getting a rough sketch together on what our routines should be in the future.

Looks like we have an equivalent of #117 reported internally as well: https://jira.op5.com/browse/MON-8745.

**Comment by jryberg** [comment]
Nice! Good work. This is wonderful :)

**Comment by nook24** [comment]
I cloned the PR to test it with my NEB module [statusenigne](https://github.com/nook24/statusengine/blob/master/statusengine/src/statusengine.c) and run into the folowing errors:
````
/tmp/foobar/statusengine.o: undefined symbol: hostescalation_ary
undefined symbol: serviceescalation_ary
undefined symbol: hostdependency_ary
undefined symbol: servicedependency_ary


undefined symbol: get_raw_command_line
Context in the neb module:
get_raw_command_line(nag_service->check_command_ptr,nag_service->check_command,&raw_command,0);
````

I guess hostescalation_ary is now hostescalation_list but what happend to get_raw_command_line()? :)

Is there a readme or something else available that neb module developers can port their modules?

**Comment by ageric** [comment]
On 2016-02-24 19:03, Daniel wrote:
> I cloned the PR to test it with my NEB module [statusenigne](https://github.com/nook24/statusengine/blob/master/statusengine/src/statusengine.c) and run into the folowing errors:
> ````
> /tmp/foobar/statusengine.o: undefined symbol: hostescalation_ary
> undefined symbol: serviceescalation_ary
> undefined symbol: hostdependency_ary
> undefined symbol: servicedependency_ary
>

Those no longer exist. The way to get to them is by accessing the
host or service and from thence hopping to the escalations or
either of the two dependency lists.

>
> undefined symbol: get_raw_command_line
> Context in the neb module:
> get_raw_command_line(nag_service->check_command_ptr,nag_service->check_command,&raw_command,0);
> ````
>
> I guess hostescalation_ary is now hostescalation_list but what happend to get_raw_command_line()? :)
>

Use get_raw_command_line_r() with get_global_macros() instead. The
syntax should be the same.


> Is there a readme or something else available that neb module developers can port their modules?
>

Unfortunately no. Widely used modules are rare enough that we decided to
forgo a migration howto. The changes shouldn't be super-honerous
though. Let me know if you run into more problems and I'll attempt to
assist as best I can.

/Andreas

**Pull request merged**
