### PR TITLE
Issue 287

### PR DESCRIPTION
**Pull request by nook24**
This should resolve issue #287 without breaking the Naemon logic.

Current behavior:
default naemon no patch

With this patch:
patched_naemon

Also some more state changes:
rainbow_test

### CODE REVIEW

**Comment by jacobbaungard** [comment]
If I understand it correctly this patch changes when `last_hard_state` is set, so that it is set after the NEB event handler callback that I assume you use to capture the results?

I see a couple of problems with this. 

1. The meaning of `last_hard_state` is now inconsistent. That is for a period of time `last_hard_state` != current_state when `state_type` is hard

2. The meaning of `last_hard_state` has now changed for other modules which are using the event handler callback

I would much prefer implementing this behavior as a separate parameter - although obviously that is a lot more work.

**Comment by ibering** [comment]
Isn't it now the same behavior like if the host is up?

https://github.com/naemon/naemon-core/blob/72aa5cbff91e994fd61383ea55ded407bd48f2f1/src/naemon/checks_service.c#L988-L993

Host is Up:
Call `handle_service_event()` and change `last_hard_state`

Host is down (without patch)
Change `last_hard_state`
https://github.com/naemon/naemon-core/blob/72aa5cbff91e994fd61383ea55ded407bd48f2f1/src/naemon/checks_service.c#L836-L857
 and call `handle_service_event()`
https://github.com/naemon/naemon-core/blob/72aa5cbff91e994fd61383ea55ded407bd48f2f1/src/naemon/checks_service.c#L881-L893
so `handle_service_event()` gets called to late I think.

---

With the patch the behavior of Naemon is the same doesn't matters if the host is up or not up. In the current implementation, there are to different behaviors.

**Comment by sni** [comment]
without having looked into details, i agree with @jacobbaungard. Also setting `last_hard_state_change` but not the actual state definitly results in an inconsistant wrong state where `last_hard_state_change` points to the current state, but the state itself is the old one.

**Comment by ibering** [comment]
But it is already inconsistent now. Why is there different behavior between host UP and host NOT UP? Please see screenshots with "Current behavior" :/

**Comment by sni** [comment]
don't get me wrong, all i am saying is, that if you move setting `last_hard_state`, move `last_hard_state_change` along with it.

**Comment by nook24** [comment]
> don't get me wrong, all i am saying is, that if you move setting last_hard_state, move last_hard_state_change along with it.

Yes that makes sense. I've fixed this

**Comment by jacobbaungard** [comment]
I missed that there is a different logic when the host is OK - that is not good.

I guess we need to decide what `last_hard_state` should mean. I.e. should it be the _previous_ hard state or the _latest_ hard state (that is including the `current_state` if `state_type` is hard), and then implement a behavior which is consistent across all states.

I always thought it as as the _latest_ hard state.

With the latest commit it is better, but I find it strange to pass some values to the event handler for them then to be immediately changed afterwards.

**Comment by jacobbaungard** [comment]
But now, when there is a hard state change to OK, we don't actually adjust `last_hard_state` at all. So that should probably be fixed as well?

**Comment by sni** [comment]
if thats the case, this should be fixed of course :-)

**Comment by nook24** [comment]
In our case we use the data provided by `broker_statechange_data` to build up a [state history](https://github.com/statusengine/worker/blob/master/lib/mysql.sql#L33-L52) for all hosts and services.

If a host is up `last_hard_state` always holds the `previous` hard state when `broker_statechange_data` gets called by Naemon.

So for me, I thought last_hard_state == previous_hard_state. Which also caused some misunderstandings in the conversation above and #291 :)

If a host is down, `last_hard_state` behaves slidely different when `broker_statechange_data` gets called it holds the current hard state. So for me this was a bug. It also makes sense for me that if the system give me a statechange event, that this event contains the previous state.

I know `last_hard_state` is also used in service status events. I never checked if it holds there the "current hard state" or the "previous hard state"...


Enjoy the weekend :)

**Comment by jacobbaungard** [comment]
While I think it is a bit odd to do the change after the after the event handler is called, I am ok with this as long as the behavior for the UP state is the same. So perhaps you could add the same logic for when there is a hard state change to UP (around L732 I believe it should be) ?

**Comment by nook24** [comment]
@jacobbaungard 
Unfortunately I'm not sure what I should do^^

Case "Services goes from HARD Critical to HARD Ok (Host is UP)":
- Call to `handle_service_event()` in [L732](https://github.com/naemon/naemon-core/blob/143f7ef6aaff5a59261c1499371a38dfd0e12089/src/naemon/checks_service.c#L732)
- Set `last_hard_state` to Ok in [L764](https://github.com/naemon/naemon-core/blob/143f7ef6aaff5a59261c1499371a38dfd0e12089/src/naemon/checks_service.c#L764)

Case "Service goes from HARD Ok to HARD Critical (Host is UP)"
- Call to `handle_service_event()` in [L910](https://github.com/naemon/naemon-core/blob/143f7ef6aaff5a59261c1499371a38dfd0e12089/src/naemon/checks_service.c#L910)
- Set `last_hard_state` in [L995](https://github.com/naemon/naemon-core/blob/143f7ef6aaff5a59261c1499371a38dfd0e12089/src/naemon/checks_service.c#L995)

Or should I move [L650](https://github.com/naemon/naemon-core/blob/143f7ef6aaff5a59261c1499371a38dfd0e12089/src/naemon/checks_service.c#L650) around?

**Comment by jacobbaungard** [comment]
Merged this, thanks!

**Pull request merged**
