### PR TITLE
Fix sprintf format error with clang

### LINKED ISSUE #314: Invalid sprintf format in objects_timeperiod
timerange2str uses int for the calculations, but %02hd for short in the output format. The clang compiler doesn't allow this and exits with an error:

```
src/naemon/objects_timeperiod.c:289:42: error: format specifies type 'short' but the argument has type 'int' [-Werror,-Wformat]
        sprintf(str, "%02hd:%02hd-%02hd:%02hd", sh, sm, eh, em);
                      ~~~~~                     ^~
                      %02d
src/naemon/objects_timeperiod.c:289:46: error: format specifies type 'short' but the argument has type 'int' [-Werror,-Wformat]
        sprintf(str, "%02hd:%02hd-%02hd:%02hd", sh, sm, eh, em);
                            ~~~~~                   ^~
                            %02d
src/naemon/objects_timeperiod.c:289:50: error: format specifies type 'short' but the argument has type 'int' [-Werror,-Wformat]
        sprintf(str, "%02hd:%02hd-%02hd:%02hd", sh, sm, eh, em);
                                  ~~~~~                 ^~
                                  %02d
src/naemon/objects_timeperiod.c:289:54: error: format specifies type 'short' but the argument has type 'int' [-Werror,-Wformat]
        sprintf(str, "%02hd:%02hd-%02hd:%02hd", sh, sm, eh, em);
                                        ~~~~~               ^~
                                        %02d
4 errors generated.
Makefile:1920: recipe for target 'src/naemon/objects_timeperiod.lo' failed
```

It compiles if I change the sprintf to this:
`sprintf(str, "%02d:%02d-%02d:%02d", sh, sm, eh, em);`

### PR DESCRIPTION
**Pull request by jabdr**
Fixes #314

### CODE REVIEW

**Comment by sni** [comment]
seems like newer gccs don't like that change:

```
[  250s] src/naemon/objects_timeperiod.c: In function 'timerange2str.part.0':
[  250s] src/naemon/objects_timeperiod.c:289:26: error: '%02d' directive writing between 2 and 7 bytes into a region of size between 1 and 6 [-Werror=format-overflow=]
[  250s]   sprintf(str, "%02d:%02d-%02d:%02d", sh, sm, eh, em);
[  250s]                           ^~~~
[  250s] src/naemon/objects_timeperiod.c:289:15: note: directive argument in the range [0, 1193046]
[  250s]   sprintf(str, "%02d:%02d-%02d:%02d", sh, sm, eh, em);
[  250s]                ^~~~~~~~~~~~~~~~~~~~~
[  250s] src/naemon/objects_timeperiod.c:289:15: note: directive argument in the range [0, 59]
[  250s] In file included from /usr/include/stdio.h:873,
[  250s]                  from src/naemon/objects_common.h:10,
[  250s]                  from src/naemon/objects_timeperiod.h:11,
[  250s]                  from src/naemon/objects_timeperiod.c:1:
[  250s] /usr/include/i386-linux-gnu/bits/stdio2.h:36:10: note: '__builtin___sprintf_chk' output between 12 and 22 bytes into a destination of size 12
[  250s]    return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
[  250s]           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[  250s]        __bos (__s), __fmt, __va_arg_pack ());
[  250s]        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[  251s] cc1: all warnings being treated as errors
[  251s] make[2]: *** [Makefile:2013: src/naemon/objects_timeperiod.lo] Error 1
[  251s] make[2]: Leaving directory '/usr/src/packages/BUILD'
[  251s] make[1]: *** [Makefile:1340: all] Error 2
[  251s] make[1]: Leaving directory '/usr/src/packages/BUILD'
[  251s] dh_auto_build: make -j1 returned exit code 2
[  251s] make: *** [debian/rules:80: build] Error 2
[  251s] dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
```

**Comment by jabdr** [comment]
@sni I think we could also change the type of sh, sm, eh, em to short and keep the format string %02hd. clang doesn't want to compile because %02hd expects a short.

**Comment by sni** [comment]
that would be better, yes

**Comment by jacobbaungard** [comment]
Ah, sigh. Perhaps we should make travis build on the same platforms as OBS.

Changing it to a `short` make sense.

**Comment by sni** [comment]
i just checked, travis does not offer any 32bit machines

**Comment by jabdr** [comment]
I created another pull request for that: https://github.com/naemon/naemon-core/pull/316

**Pull request merged**
